# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

controllers:
    resource: routing.controllers

#hello_page:
#    path: /hello
#    controller: App\Controller\DefaultController::hello
blog_show:
    path: /blog/{id}
    controller: App\Controller\BlogController::show
    defaults:
        page: 1
    requirements:
        id: '\d+'
contact_page:
    path: /contact
    controller: App\Controller\ContactController::index()

product_page:
    path: /poduct/{slug}
    controller: App\Controller\ProductController::index()
    requirements:
        name: '[\a-zA-Z-]+'
